<?php

namespace MobileCart\SubscriptionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPaymentRepository extends EntityRepository
{
}
